# Generated by Django 5.0.3 on 2024-04-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('manager', 'Manager'), ('chef', 'Chef')], default='buyer', max_length=20),
        ),
    ]
