# Generated by Django 5.0.3 on 2024-03-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('class_name', models.CharField(default='pizza', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_product', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('class_name', models.CharField(default='sets', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_product', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Sushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('class_name', models.CharField(default='sushi', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_product', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
